/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import Button from "@/components/ui/Button";

const primaryButton = {
  text: "Call for Estimate",
  href: "#"
};

const ContactInline = () => {
  return (
    <section aria-label="Contact section" className="py-20">
      <div className="w-content-width mx-auto">
        <ScrollReveal variant="fade-blur">
          <div className="flex flex-col items-center gap-8 md:gap-10 py-20 px-8 rounded card">
            <div className="flex flex-col items-center gap-2">
              <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
                <p>{"Emergency Service"}</p>
              </div>

              <TextAnimation
                text={"Ready to experience precision comfort?"}
                variant={"fade-blur"}
                gradientText={true}
                tag="h2"
                className="md:max-w-8/10 text-5xl 2xl:text-6xl leading-[1.15] font-semibold text-center text-balance"
              />

              <form className="w-full max-w-lg flex flex-col gap-4 mt-6 text-left" onSubmit={(e) => e.preventDefault()}>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="flex flex-col gap-1.5">
                    <label className="text-xs font-medium text-accent">Name</label>
                    <input
                      type="text"
                      required
                      placeholder="Your Name"
                      className="w-full px-4 py-2.5 rounded bg-background border border-accent/20 text-foreground focus:outline-none focus:border-foreground/50 text-sm"
                    />
                  </div>
                  <div className="flex flex-col gap-1.5">
                    <label className="text-xs font-medium text-accent">Phone Number</label>
                    <input
                      type="tel"
                      required
                      placeholder="(555) 000-0000"
                      className="w-full px-4 py-2.5 rounded bg-background border border-accent/20 text-foreground focus:outline-none focus:border-foreground/50 text-sm"
                    />
                  </div>
                </div>
                <div className="flex flex-col gap-1.5">
                  <label className="text-xs font-medium text-accent">City</label>
                  <input
                    type="text"
                    required
                    placeholder="Your City"
                    className="w-full px-4 py-2.5 rounded bg-background border border-accent/20 text-foreground focus:outline-none focus:border-foreground/50 text-sm"
                  />
                </div>
                <div className="flex flex-col gap-1.5">
                  <label className="text-xs font-medium text-accent">What's wrong?</label>
                  <textarea
                    required
                    rows={4}
                    placeholder="Describe the issue with your HVAC system..."
                    className="w-full px-4 py-2.5 rounded bg-background border border-accent/20 text-foreground focus:outline-none focus:border-foreground/50 text-sm resize-none"
                  />
                </div>
                <button
                  type="submit"
                  className="mt-2 w-full primary-button py-3 px-6 rounded font-medium transition cursor-pointer text-center"
                >
                  Call for Estimate
                </button>
              </form>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ContactSection() {
  return (
    <div data-webild-section="contact" data-section="contact" id="contact">
      <ContactInline />
    </div>
  );
}
