// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Support"
          title="Common Inquiries"
          description="Expert answers to maintain your high-performance home."
          categories={[
            {
              name: "Maintenance",
              items: [
                {
                  question: "How often?",
                  answer: "Twice per year.",
                },
                {
                  question: "Cost?",
                  answer: "Depends on system.",
                },
              ],
            },
            {
              name: "Installation",
              items: [
                {
                  question: "Timeframe?",
                  answer: "1-2 days.",
                },
                {
                  question: "Warranty?",
                  answer: "Full factory warranty.",
                },
              ],
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
