// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesTaggedCards from '@/components/sections/features/FeaturesTaggedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesTaggedCards
          tag="Our Expertise"
          title="Integrated Climate Solutions"
          description="Comprehensive climate control delivered with unmatched precision."
          items={[
            {
              tag: "Install",
              title: "AC Installation",
              description: "Seamless installation of high-efficiency systems.",
              primaryButton: {
                text: "Learn More",
                href: "#",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/vertical-portrait-young-woman-fitness-instructor-mindfulness-coach-sitting-floor-home_1258-200338.jpg",
            },
            {
              tag: "Repair",
              title: "Heating Repair",
              description: "Rapid, effective resolution to complex heating issues.",
              primaryButton: {
                text: "Learn More",
                href: "#",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/smiley-woman-sitting-near-heater-home_23-2149335095.jpg",
            },
            {
              tag: "Air",
              title: "Air Quality",
              description: "Pioneering technology for pure home environments.",
              primaryButton: {
                text: "Learn More",
                href: "#",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/asian-man-with-cancer-outside-side-view_23-2149870334.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
