/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";

const primaryButton = {
  text: "GET A FREE ESTIMATE",
  href: "#contact"
};
const secondaryButton = {
  text: "EXPLORE SERVICES",
  href: "#features"
};
const leftItems = [
  {
    imageSrc: "http://img.b2bpic.net/free-photo/luxurious-villa-with-modern-architectural-design_23-2151694017.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/gray-concrete-stairs-inside-building_250224-97.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/crop-woman-showing-tablet_23-2147809527.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/home-plant-vase-decoration-composition_23-2149090621.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/low-angle-shot-grey-concrete-building-representing-modern-architecture_181624-4719.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/view-modern-futuristic-work-space-with-furniture_23-2151797641.jpg"
  }
];
const rightItems = [
  {
    imageSrc: "http://img.b2bpic.net/free-photo/digital-tunnel-abstract_23-2151977844.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/low-angle-edge-modern-building_23-2148287782.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/3d-rendering-industry-40-concept_23-2149408301.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/building-structure_1127-2019.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/wireless-router-with-copy-space_23-2148295822.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/beautiful-light-lamp-bulb-decoration-interior-room_74190-7930.jpg"
  }
];

type HeroSplitVerticalMarqueeProps = {
  tag: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  leftItems: ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never })[];
  rightItems: ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never })[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
};

const HeroInline = () => {
  const duplicatedLeft = [...leftItems, ...leftItems, ...leftItems, ...leftItems];
  const duplicatedRight = [...rightItems, ...rightItems, ...rightItems, ...rightItems];

  return (
    <section aria-label="Hero section" className="relative flex items-center h-fit md:h-svh pt-25 pb-20 md:py-0">
      <HeroBackgroundSlot />
      <div className="flex flex-col md:flex-row items-center gap-12 md:gap-20 w-content-width mx-auto">
        <div className="w-full md:w-1/2">
          <div className="flex flex-col items-center md:items-start gap-3">
            <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
              <p>{"HVAC ENGINEERING EXCELLENCE"}</p>
            </div>

            <TextAnimation
              text={"COMFORT, ENGINEERED."}
              variant={"fade-blur"}
              gradientText={true}
              tag="h1"
              className="text-4xl sm:text-5xl lg:text-6xl xl:text-7xl leading-[1.1] font-semibold text-center md:text-left text-balance"
            />

            <TextAnimation
              text={"High-performance heating and cooling systems designed, installed, and maintained for the way you live."}
              variant={"fade-blur"}
              gradientText={false}
              tag="p"
              className="md:max-w-8/10 text-lg md:text-xl leading-snug text-center md:text-left text-balance"
            />

            <div className="flex flex-wrap max-md:justify-center gap-3 mt-2 md:mt-3">
              <Button text={primaryButton.text} href={primaryButton.href} variant="primary"/>
              <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary"animationDelay={0.1} />
            </div>
          </div>
        </div>

        <div className="w-full md:w-1/2 h-100 md:h-[75vh] flex gap-2 xl:gap-3 2xl:gap-4 overflow-hidden">
          <div className="flex-1 overflow-hidden mask-fade-y-medium">
            <div className="flex flex-col gap-2 xl:gap-3 2xl:gap-4 animate-marquee-vertical">
              {duplicatedLeft.map((item, index) => (
                <div key={index} className="shrink-0 aspect-square p-1 xl:p-2 2xl:p-3 card rounded overflow-hidden">
                  <ImageOrVideo imageSrc={item.imageSrc} videoSrc={item.videoSrc} />
                </div>
              ))}
            </div>
          </div>

          <div className="flex-1 overflow-hidden mask-fade-y-medium">
            <div className="flex flex-col gap-2 xl:gap-3 2xl:gap-4 animate-marquee-vertical-reverse">
              {duplicatedRight.map((item, index) => (
                <div key={index} className="shrink-0 aspect-square p-1 xl:p-2 2xl:p-3 card rounded overflow-hidden">
                  <ImageOrVideo imageSrc={item.imageSrc} videoSrc={item.videoSrc} />
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default function HeroSection() {
  return (
    <div data-webild-section="hero" data-section="hero" id="hero">
      <HeroInline />
    </div>
  );
}
