// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsMediaCards
          tag="Our Impact"
          title="Performance at Scale"
          description="Quantifiable excellence across every project we touch."
          metrics={[
            {
              value: "15k+",
              title: "Systems Installed",
              description: "Precision performance across thousands of homes.",
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-woman-working-blue-print-while-her-colleague-discussing-something-background_23-2148187235.jpg",
            },
            {
              value: "99.2%",
              title: "Efficiency Rating",
              description: "Optimized power consumption for longevity.",
              imageSrc: "http://img.b2bpic.net/free-photo/digital-dashboard_23-2151957114.jpg",
            },
            {
              value: "24/7",
              title: "Response Time",
              description: "Always-on service for your critical needs.",
              imageSrc: "http://img.b2bpic.net/free-photo/builder-man-wearing-construction-uniform-security-helmet-talking-mobile-phone-smiling-showing-thumb-up-camera-standing-isolated-orange-wall_141793-14177.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
