// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesImageBento
          tag="Bento Grid"
          title="Core Offerings"
          description="A refined collection of high-end HVAC services."
          items={[
            {
              title: "AC Install",
              description: "Modern cooling.",
              imageSrc: "http://img.b2bpic.net/free-photo/man-performing-artistic-dance-rooftop-with-blue-sky_23-2149144406.jpg",
            },
            {
              title: "AC Repair",
              description: "Rapid restoration.",
              imageSrc: "http://img.b2bpic.net/free-photo/car-mechanic-wearing-white-uniform-stand-holding-wrench_1150-16596.jpg",
            },
            {
              title: "Heating Install",
              description: "Thermal excellence.",
              imageSrc: "http://img.b2bpic.net/free-photo/modern-autonomous-heating-system-boiler-room_169016-51414.jpg",
            },
            {
              title: "Heating Repair",
              description: "Quick fix.",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-people-wearing-helmets-work_23-2149366667.jpg",
            },
            {
              title: "Maintenance",
              description: "Longevity focused.",
              imageSrc: "http://img.b2bpic.net/free-photo/futuristic-kitchen-interior-design_23-2151821342.jpg",
            },
            {
              title: "Indoor Air",
              description: "Breathe pure.",
              imageSrc: "http://img.b2bpic.net/free-photo/man-turning-off-thermostat-energy-crisis_23-2150061798.jpg",
            },
            {
              title: "Commercial",
              description: "Scalable systems.",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-heat-pump-outside-home_23-2149250243.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
