// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialQuoteCards from '@/components/sections/testimonial/TestimonialQuoteCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialQuoteCards
          tag="Verified Quality"
          title="Trusted by Professionals"
          description="Client success is our performance indicator."
          testimonials={[
            {
              name: "Sarah Miller",
              role: "Architect",
              quote: "Northstar delivers engineering-level precision in residential heating.",
              imageSrc: "http://img.b2bpic.net/free-photo/female-editor-designer-retouches-photos-dual-monitors-desktop_482257-126858.jpg",
            },
            {
              name: "James Vance",
              role: "Commercial Property Manager",
              quote: "Reliability redefined. Their maintenance is second to none.",
              imageSrc: "http://img.b2bpic.net/free-photo/young-businessman-angry-expression_1194-1680.jpg",
            },
            {
              name: "David Sterling",
              role: "Luxury Homeowner",
              quote: "The quietest system I've ever owned. Professional grade.",
              imageSrc: "http://img.b2bpic.net/free-photo/fashionable-young-woman-posing-with-suitcase-standing-hotel-hallway_23-2148033329.jpg",
            },
            {
              name: "Elena Ross",
              role: "Property Owner",
              quote: "Exceptional communication and clean, professional installs.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-business-woman-with-folded-hands-against-white-wall-toothy-smile-crossed-arms_231208-10801.jpg",
            },
            {
              name: "Marcus Thorne",
              role: "Interior Designer",
              quote: "They integrate systems into spaces without disrupting design.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-photographer-posing_23-2148019162.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
