/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import GridOrCarousel from "@/components/ui/GridOrCarousel";
import ScrollReveal from "@/components/ui/ScrollReveal";

const testimonials = [
  {
    name: "Sarah Miller",
    role: "Architect",
    quote: "Northstar delivers engineering-level precision in residential heating.",
    imageSrc: "http://img.b2bpic.net/free-photo/female-editor-designer-retouches-photos-dual-monitors-desktop_482257-126858.jpg"
  },
  {
    name: "James Vance",
    role: "Commercial Property Manager",
    quote: "Reliability redefined. Their maintenance is second to none.",
    imageSrc: "http://img.b2bpic.net/free-photo/young-businessman-angry-expression_1194-1680.jpg"
  },
  {
    name: "David Sterling",
    role: "Luxury Homeowner",
    quote: "The quietest system I've ever owned. Professional grade.",
    imageSrc: "http://img.b2bpic.net/free-photo/fashionable-young-woman-posing-with-suitcase-standing-hotel-hallway_23-2148033329.jpg"
  },
  {
    name: "Elena Ross",
    role: "Property Owner",
    quote: "Exceptional communication and clean, professional installs.",
    imageSrc: "http://img.b2bpic.net/free-photo/smiling-business-woman-with-folded-hands-against-white-wall-toothy-smile-crossed-arms_231208-10801.jpg"
  },
  {
    name: "Marcus Thorne",
    role: "Interior Designer",
    quote: "They integrate systems into spaces without disrupting design.",
    imageSrc: "http://img.b2bpic.net/free-photo/smiling-photographer-posing_23-2148019162.jpg"
  }
];

type Testimonial = {
  name: string;
  role: string;
  quote: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const TestimonialsInline = () => (
  <section aria-label="Testimonials section" className="py-20">
    <div className="flex flex-col gap-8 md:gap-10">
      <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Verified Quality"}</p>
        </div>

        <TextAnimation
          text={"Trusted by Professionals"}
          variant={"fade-blur"}
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Client success is our performance indicator."}
          variant={"fade-blur"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
          </div>
        )}
      </div>

      <ScrollReveal variant="fade">
        <GridOrCarousel >
          {testimonials.map((testimonial) => (
            <div key={testimonial.name} className="flex flex-col gap-4 xl:gap-5 2xl:gap-6 p-6 xl:p-7 2xl:p-8 card rounded items-center text-center">
              <div className="relative size-22 xl:size-24 2xl:size-26 overflow-hidden rounded-full mx-auto">
                <ImageOrVideo imageSrc={testimonial.imageSrc} videoSrc={testimonial.videoSrc} />
              </div>

              <div className="flex flex-col">
                <span className="text-2xl font-semibold leading-snug truncate">{testimonial.name}</span>
                <span className="text-base leading-snug opacity-75 truncate">{testimonial.role}</span>
              </div>

              <p className="text-lg leading-snug">{testimonial.quote}</p>
            </div>
          ))}
        </GridOrCarousel>
      </ScrollReveal>
    </div>
  </section>
);

export default function TestimonialsSection() {
  return (
    <div data-webild-section="testimonials" data-section="testimonials" id="testimonials">
      <TestimonialsInline />
    </div>
  );
}
